# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nick/src/zydis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nick/src/zydis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/src/zydis/CMakeFiles /home/nick/src/zydis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/src/zydis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Zydis

# Build rule for target.
Zydis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Zydis
.PHONY : Zydis

# fast build rule for target.
Zydis/fast:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/build
.PHONY : Zydis/fast

#=============================================================================
# Target rules for targets named ZydisPerfTest

# Build rule for target.
ZydisPerfTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZydisPerfTest
.PHONY : ZydisPerfTest

# fast build rule for target.
ZydisPerfTest/fast:
	$(MAKE) -f CMakeFiles/ZydisPerfTest.dir/build.make CMakeFiles/ZydisPerfTest.dir/build
.PHONY : ZydisPerfTest/fast

#=============================================================================
# Target rules for targets named Formatter02

# Build rule for target.
Formatter02: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Formatter02
.PHONY : Formatter02

# fast build rule for target.
Formatter02/fast:
	$(MAKE) -f CMakeFiles/Formatter02.dir/build.make CMakeFiles/Formatter02.dir/build
.PHONY : Formatter02/fast

#=============================================================================
# Target rules for targets named Formatter01

# Build rule for target.
Formatter01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Formatter01
.PHONY : Formatter01

# fast build rule for target.
Formatter01/fast:
	$(MAKE) -f CMakeFiles/Formatter01.dir/build.make CMakeFiles/Formatter01.dir/build
.PHONY : Formatter01/fast

#=============================================================================
# Target rules for targets named EncodeFromScratch

# Build rule for target.
EncodeFromScratch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EncodeFromScratch
.PHONY : EncodeFromScratch

# fast build rule for target.
EncodeFromScratch/fast:
	$(MAKE) -f CMakeFiles/EncodeFromScratch.dir/build.make CMakeFiles/EncodeFromScratch.dir/build
.PHONY : EncodeFromScratch/fast

#=============================================================================
# Target rules for targets named RewriteCode

# Build rule for target.
RewriteCode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RewriteCode
.PHONY : RewriteCode

# fast build rule for target.
RewriteCode/fast:
	$(MAKE) -f CMakeFiles/RewriteCode.dir/build.make CMakeFiles/RewriteCode.dir/build
.PHONY : RewriteCode/fast

#=============================================================================
# Target rules for targets named ZydisDisasm

# Build rule for target.
ZydisDisasm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZydisDisasm
.PHONY : ZydisDisasm

# fast build rule for target.
ZydisDisasm/fast:
	$(MAKE) -f CMakeFiles/ZydisDisasm.dir/build.make CMakeFiles/ZydisDisasm.dir/build
.PHONY : ZydisDisasm/fast

#=============================================================================
# Target rules for targets named ZydisFuzzDecoder

# Build rule for target.
ZydisFuzzDecoder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZydisFuzzDecoder
.PHONY : ZydisFuzzDecoder

# fast build rule for target.
ZydisFuzzDecoder/fast:
	$(MAKE) -f CMakeFiles/ZydisFuzzDecoder.dir/build.make CMakeFiles/ZydisFuzzDecoder.dir/build
.PHONY : ZydisFuzzDecoder/fast

#=============================================================================
# Target rules for targets named ZydisFuzzEncoder

# Build rule for target.
ZydisFuzzEncoder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZydisFuzzEncoder
.PHONY : ZydisFuzzEncoder

# fast build rule for target.
ZydisFuzzEncoder/fast:
	$(MAKE) -f CMakeFiles/ZydisFuzzEncoder.dir/build.make CMakeFiles/ZydisFuzzEncoder.dir/build
.PHONY : ZydisFuzzEncoder/fast

#=============================================================================
# Target rules for targets named ZydisTestEncoderAbsolute

# Build rule for target.
ZydisTestEncoderAbsolute: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZydisTestEncoderAbsolute
.PHONY : ZydisTestEncoderAbsolute

# fast build rule for target.
ZydisTestEncoderAbsolute/fast:
	$(MAKE) -f CMakeFiles/ZydisTestEncoderAbsolute.dir/build.make CMakeFiles/ZydisTestEncoderAbsolute.dir/build
.PHONY : ZydisTestEncoderAbsolute/fast

#=============================================================================
# Target rules for targets named Formatter03

# Build rule for target.
Formatter03: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Formatter03
.PHONY : Formatter03

# fast build rule for target.
Formatter03/fast:
	$(MAKE) -f CMakeFiles/Formatter03.dir/build.make CMakeFiles/Formatter03.dir/build
.PHONY : Formatter03/fast

#=============================================================================
# Target rules for targets named ZydisFuzzReEncoding

# Build rule for target.
ZydisFuzzReEncoding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZydisFuzzReEncoding
.PHONY : ZydisFuzzReEncoding

# fast build rule for target.
ZydisFuzzReEncoding/fast:
	$(MAKE) -f CMakeFiles/ZydisFuzzReEncoding.dir/build.make CMakeFiles/ZydisFuzzReEncoding.dir/build
.PHONY : ZydisFuzzReEncoding/fast

#=============================================================================
# Target rules for targets named ZydisInfo

# Build rule for target.
ZydisInfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZydisInfo
.PHONY : ZydisInfo

# fast build rule for target.
ZydisInfo/fast:
	$(MAKE) -f CMakeFiles/ZydisInfo.dir/build.make CMakeFiles/ZydisInfo.dir/build
.PHONY : ZydisInfo/fast

#=============================================================================
# Target rules for targets named Zycore

# Build rule for target.
Zycore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Zycore
.PHONY : Zycore

# fast build rule for target.
Zycore/fast:
	$(MAKE) -f zycore/CMakeFiles/Zycore.dir/build.make zycore/CMakeFiles/Zycore.dir/build
.PHONY : Zycore/fast

examples/EncodeFromScratch.o: examples/EncodeFromScratch.c.o

.PHONY : examples/EncodeFromScratch.o

# target to build an object file
examples/EncodeFromScratch.c.o:
	$(MAKE) -f CMakeFiles/EncodeFromScratch.dir/build.make CMakeFiles/EncodeFromScratch.dir/examples/EncodeFromScratch.c.o
.PHONY : examples/EncodeFromScratch.c.o

examples/EncodeFromScratch.i: examples/EncodeFromScratch.c.i

.PHONY : examples/EncodeFromScratch.i

# target to preprocess a source file
examples/EncodeFromScratch.c.i:
	$(MAKE) -f CMakeFiles/EncodeFromScratch.dir/build.make CMakeFiles/EncodeFromScratch.dir/examples/EncodeFromScratch.c.i
.PHONY : examples/EncodeFromScratch.c.i

examples/EncodeFromScratch.s: examples/EncodeFromScratch.c.s

.PHONY : examples/EncodeFromScratch.s

# target to generate assembly for a file
examples/EncodeFromScratch.c.s:
	$(MAKE) -f CMakeFiles/EncodeFromScratch.dir/build.make CMakeFiles/EncodeFromScratch.dir/examples/EncodeFromScratch.c.s
.PHONY : examples/EncodeFromScratch.c.s

examples/Formatter01.o: examples/Formatter01.c.o

.PHONY : examples/Formatter01.o

# target to build an object file
examples/Formatter01.c.o:
	$(MAKE) -f CMakeFiles/Formatter01.dir/build.make CMakeFiles/Formatter01.dir/examples/Formatter01.c.o
.PHONY : examples/Formatter01.c.o

examples/Formatter01.i: examples/Formatter01.c.i

.PHONY : examples/Formatter01.i

# target to preprocess a source file
examples/Formatter01.c.i:
	$(MAKE) -f CMakeFiles/Formatter01.dir/build.make CMakeFiles/Formatter01.dir/examples/Formatter01.c.i
.PHONY : examples/Formatter01.c.i

examples/Formatter01.s: examples/Formatter01.c.s

.PHONY : examples/Formatter01.s

# target to generate assembly for a file
examples/Formatter01.c.s:
	$(MAKE) -f CMakeFiles/Formatter01.dir/build.make CMakeFiles/Formatter01.dir/examples/Formatter01.c.s
.PHONY : examples/Formatter01.c.s

examples/Formatter02.o: examples/Formatter02.c.o

.PHONY : examples/Formatter02.o

# target to build an object file
examples/Formatter02.c.o:
	$(MAKE) -f CMakeFiles/Formatter02.dir/build.make CMakeFiles/Formatter02.dir/examples/Formatter02.c.o
.PHONY : examples/Formatter02.c.o

examples/Formatter02.i: examples/Formatter02.c.i

.PHONY : examples/Formatter02.i

# target to preprocess a source file
examples/Formatter02.c.i:
	$(MAKE) -f CMakeFiles/Formatter02.dir/build.make CMakeFiles/Formatter02.dir/examples/Formatter02.c.i
.PHONY : examples/Formatter02.c.i

examples/Formatter02.s: examples/Formatter02.c.s

.PHONY : examples/Formatter02.s

# target to generate assembly for a file
examples/Formatter02.c.s:
	$(MAKE) -f CMakeFiles/Formatter02.dir/build.make CMakeFiles/Formatter02.dir/examples/Formatter02.c.s
.PHONY : examples/Formatter02.c.s

examples/Formatter03.o: examples/Formatter03.c.o

.PHONY : examples/Formatter03.o

# target to build an object file
examples/Formatter03.c.o:
	$(MAKE) -f CMakeFiles/Formatter03.dir/build.make CMakeFiles/Formatter03.dir/examples/Formatter03.c.o
.PHONY : examples/Formatter03.c.o

examples/Formatter03.i: examples/Formatter03.c.i

.PHONY : examples/Formatter03.i

# target to preprocess a source file
examples/Formatter03.c.i:
	$(MAKE) -f CMakeFiles/Formatter03.dir/build.make CMakeFiles/Formatter03.dir/examples/Formatter03.c.i
.PHONY : examples/Formatter03.c.i

examples/Formatter03.s: examples/Formatter03.c.s

.PHONY : examples/Formatter03.s

# target to generate assembly for a file
examples/Formatter03.c.s:
	$(MAKE) -f CMakeFiles/Formatter03.dir/build.make CMakeFiles/Formatter03.dir/examples/Formatter03.c.s
.PHONY : examples/Formatter03.c.s

examples/RewriteCode.o: examples/RewriteCode.c.o

.PHONY : examples/RewriteCode.o

# target to build an object file
examples/RewriteCode.c.o:
	$(MAKE) -f CMakeFiles/RewriteCode.dir/build.make CMakeFiles/RewriteCode.dir/examples/RewriteCode.c.o
.PHONY : examples/RewriteCode.c.o

examples/RewriteCode.i: examples/RewriteCode.c.i

.PHONY : examples/RewriteCode.i

# target to preprocess a source file
examples/RewriteCode.c.i:
	$(MAKE) -f CMakeFiles/RewriteCode.dir/build.make CMakeFiles/RewriteCode.dir/examples/RewriteCode.c.i
.PHONY : examples/RewriteCode.c.i

examples/RewriteCode.s: examples/RewriteCode.c.s

.PHONY : examples/RewriteCode.s

# target to generate assembly for a file
examples/RewriteCode.c.s:
	$(MAKE) -f CMakeFiles/RewriteCode.dir/build.make CMakeFiles/RewriteCode.dir/examples/RewriteCode.c.s
.PHONY : examples/RewriteCode.c.s

examples/ZydisPerfTest.o: examples/ZydisPerfTest.c.o

.PHONY : examples/ZydisPerfTest.o

# target to build an object file
examples/ZydisPerfTest.c.o:
	$(MAKE) -f CMakeFiles/ZydisPerfTest.dir/build.make CMakeFiles/ZydisPerfTest.dir/examples/ZydisPerfTest.c.o
.PHONY : examples/ZydisPerfTest.c.o

examples/ZydisPerfTest.i: examples/ZydisPerfTest.c.i

.PHONY : examples/ZydisPerfTest.i

# target to preprocess a source file
examples/ZydisPerfTest.c.i:
	$(MAKE) -f CMakeFiles/ZydisPerfTest.dir/build.make CMakeFiles/ZydisPerfTest.dir/examples/ZydisPerfTest.c.i
.PHONY : examples/ZydisPerfTest.c.i

examples/ZydisPerfTest.s: examples/ZydisPerfTest.c.s

.PHONY : examples/ZydisPerfTest.s

# target to generate assembly for a file
examples/ZydisPerfTest.c.s:
	$(MAKE) -f CMakeFiles/ZydisPerfTest.dir/build.make CMakeFiles/ZydisPerfTest.dir/examples/ZydisPerfTest.c.s
.PHONY : examples/ZydisPerfTest.c.s

src/Decoder.o: src/Decoder.c.o

.PHONY : src/Decoder.o

# target to build an object file
src/Decoder.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Decoder.c.o
.PHONY : src/Decoder.c.o

src/Decoder.i: src/Decoder.c.i

.PHONY : src/Decoder.i

# target to preprocess a source file
src/Decoder.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Decoder.c.i
.PHONY : src/Decoder.c.i

src/Decoder.s: src/Decoder.c.s

.PHONY : src/Decoder.s

# target to generate assembly for a file
src/Decoder.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Decoder.c.s
.PHONY : src/Decoder.c.s

src/DecoderData.o: src/DecoderData.c.o

.PHONY : src/DecoderData.o

# target to build an object file
src/DecoderData.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/DecoderData.c.o
.PHONY : src/DecoderData.c.o

src/DecoderData.i: src/DecoderData.c.i

.PHONY : src/DecoderData.i

# target to preprocess a source file
src/DecoderData.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/DecoderData.c.i
.PHONY : src/DecoderData.c.i

src/DecoderData.s: src/DecoderData.c.s

.PHONY : src/DecoderData.s

# target to generate assembly for a file
src/DecoderData.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/DecoderData.c.s
.PHONY : src/DecoderData.c.s

src/Encoder.o: src/Encoder.c.o

.PHONY : src/Encoder.o

# target to build an object file
src/Encoder.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Encoder.c.o
.PHONY : src/Encoder.c.o

src/Encoder.i: src/Encoder.c.i

.PHONY : src/Encoder.i

# target to preprocess a source file
src/Encoder.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Encoder.c.i
.PHONY : src/Encoder.c.i

src/Encoder.s: src/Encoder.c.s

.PHONY : src/Encoder.s

# target to generate assembly for a file
src/Encoder.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Encoder.c.s
.PHONY : src/Encoder.c.s

src/EncoderData.o: src/EncoderData.c.o

.PHONY : src/EncoderData.o

# target to build an object file
src/EncoderData.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/EncoderData.c.o
.PHONY : src/EncoderData.c.o

src/EncoderData.i: src/EncoderData.c.i

.PHONY : src/EncoderData.i

# target to preprocess a source file
src/EncoderData.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/EncoderData.c.i
.PHONY : src/EncoderData.c.i

src/EncoderData.s: src/EncoderData.c.s

.PHONY : src/EncoderData.s

# target to generate assembly for a file
src/EncoderData.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/EncoderData.c.s
.PHONY : src/EncoderData.c.s

src/Formatter.o: src/Formatter.c.o

.PHONY : src/Formatter.o

# target to build an object file
src/Formatter.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Formatter.c.o
.PHONY : src/Formatter.c.o

src/Formatter.i: src/Formatter.c.i

.PHONY : src/Formatter.i

# target to preprocess a source file
src/Formatter.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Formatter.c.i
.PHONY : src/Formatter.c.i

src/Formatter.s: src/Formatter.c.s

.PHONY : src/Formatter.s

# target to generate assembly for a file
src/Formatter.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Formatter.c.s
.PHONY : src/Formatter.c.s

src/FormatterATT.o: src/FormatterATT.c.o

.PHONY : src/FormatterATT.o

# target to build an object file
src/FormatterATT.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterATT.c.o
.PHONY : src/FormatterATT.c.o

src/FormatterATT.i: src/FormatterATT.c.i

.PHONY : src/FormatterATT.i

# target to preprocess a source file
src/FormatterATT.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterATT.c.i
.PHONY : src/FormatterATT.c.i

src/FormatterATT.s: src/FormatterATT.c.s

.PHONY : src/FormatterATT.s

# target to generate assembly for a file
src/FormatterATT.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterATT.c.s
.PHONY : src/FormatterATT.c.s

src/FormatterBase.o: src/FormatterBase.c.o

.PHONY : src/FormatterBase.o

# target to build an object file
src/FormatterBase.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterBase.c.o
.PHONY : src/FormatterBase.c.o

src/FormatterBase.i: src/FormatterBase.c.i

.PHONY : src/FormatterBase.i

# target to preprocess a source file
src/FormatterBase.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterBase.c.i
.PHONY : src/FormatterBase.c.i

src/FormatterBase.s: src/FormatterBase.c.s

.PHONY : src/FormatterBase.s

# target to generate assembly for a file
src/FormatterBase.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterBase.c.s
.PHONY : src/FormatterBase.c.s

src/FormatterBuffer.o: src/FormatterBuffer.c.o

.PHONY : src/FormatterBuffer.o

# target to build an object file
src/FormatterBuffer.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterBuffer.c.o
.PHONY : src/FormatterBuffer.c.o

src/FormatterBuffer.i: src/FormatterBuffer.c.i

.PHONY : src/FormatterBuffer.i

# target to preprocess a source file
src/FormatterBuffer.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterBuffer.c.i
.PHONY : src/FormatterBuffer.c.i

src/FormatterBuffer.s: src/FormatterBuffer.c.s

.PHONY : src/FormatterBuffer.s

# target to generate assembly for a file
src/FormatterBuffer.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterBuffer.c.s
.PHONY : src/FormatterBuffer.c.s

src/FormatterIntel.o: src/FormatterIntel.c.o

.PHONY : src/FormatterIntel.o

# target to build an object file
src/FormatterIntel.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterIntel.c.o
.PHONY : src/FormatterIntel.c.o

src/FormatterIntel.i: src/FormatterIntel.c.i

.PHONY : src/FormatterIntel.i

# target to preprocess a source file
src/FormatterIntel.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterIntel.c.i
.PHONY : src/FormatterIntel.c.i

src/FormatterIntel.s: src/FormatterIntel.c.s

.PHONY : src/FormatterIntel.s

# target to generate assembly for a file
src/FormatterIntel.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/FormatterIntel.c.s
.PHONY : src/FormatterIntel.c.s

src/MetaInfo.o: src/MetaInfo.c.o

.PHONY : src/MetaInfo.o

# target to build an object file
src/MetaInfo.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/MetaInfo.c.o
.PHONY : src/MetaInfo.c.o

src/MetaInfo.i: src/MetaInfo.c.i

.PHONY : src/MetaInfo.i

# target to preprocess a source file
src/MetaInfo.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/MetaInfo.c.i
.PHONY : src/MetaInfo.c.i

src/MetaInfo.s: src/MetaInfo.c.s

.PHONY : src/MetaInfo.s

# target to generate assembly for a file
src/MetaInfo.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/MetaInfo.c.s
.PHONY : src/MetaInfo.c.s

src/Mnemonic.o: src/Mnemonic.c.o

.PHONY : src/Mnemonic.o

# target to build an object file
src/Mnemonic.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Mnemonic.c.o
.PHONY : src/Mnemonic.c.o

src/Mnemonic.i: src/Mnemonic.c.i

.PHONY : src/Mnemonic.i

# target to preprocess a source file
src/Mnemonic.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Mnemonic.c.i
.PHONY : src/Mnemonic.c.i

src/Mnemonic.s: src/Mnemonic.c.s

.PHONY : src/Mnemonic.s

# target to generate assembly for a file
src/Mnemonic.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Mnemonic.c.s
.PHONY : src/Mnemonic.c.s

src/Register.o: src/Register.c.o

.PHONY : src/Register.o

# target to build an object file
src/Register.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Register.c.o
.PHONY : src/Register.c.o

src/Register.i: src/Register.c.i

.PHONY : src/Register.i

# target to preprocess a source file
src/Register.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Register.c.i
.PHONY : src/Register.c.i

src/Register.s: src/Register.c.s

.PHONY : src/Register.s

# target to generate assembly for a file
src/Register.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Register.c.s
.PHONY : src/Register.c.s

src/Segment.o: src/Segment.c.o

.PHONY : src/Segment.o

# target to build an object file
src/Segment.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Segment.c.o
.PHONY : src/Segment.c.o

src/Segment.i: src/Segment.c.i

.PHONY : src/Segment.i

# target to preprocess a source file
src/Segment.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Segment.c.i
.PHONY : src/Segment.c.i

src/Segment.s: src/Segment.c.s

.PHONY : src/Segment.s

# target to generate assembly for a file
src/Segment.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Segment.c.s
.PHONY : src/Segment.c.s

src/SharedData.o: src/SharedData.c.o

.PHONY : src/SharedData.o

# target to build an object file
src/SharedData.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/SharedData.c.o
.PHONY : src/SharedData.c.o

src/SharedData.i: src/SharedData.c.i

.PHONY : src/SharedData.i

# target to preprocess a source file
src/SharedData.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/SharedData.c.i
.PHONY : src/SharedData.c.i

src/SharedData.s: src/SharedData.c.s

.PHONY : src/SharedData.s

# target to generate assembly for a file
src/SharedData.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/SharedData.c.s
.PHONY : src/SharedData.c.s

src/String.o: src/String.c.o

.PHONY : src/String.o

# target to build an object file
src/String.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/String.c.o
.PHONY : src/String.c.o

src/String.i: src/String.c.i

.PHONY : src/String.i

# target to preprocess a source file
src/String.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/String.c.i
.PHONY : src/String.c.i

src/String.s: src/String.c.s

.PHONY : src/String.s

# target to generate assembly for a file
src/String.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/String.c.s
.PHONY : src/String.c.s

src/Utils.o: src/Utils.c.o

.PHONY : src/Utils.o

# target to build an object file
src/Utils.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Utils.c.o
.PHONY : src/Utils.c.o

src/Utils.i: src/Utils.c.i

.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Utils.c.i
.PHONY : src/Utils.c.i

src/Utils.s: src/Utils.c.s

.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Utils.c.s
.PHONY : src/Utils.c.s

src/Zydis.o: src/Zydis.c.o

.PHONY : src/Zydis.o

# target to build an object file
src/Zydis.c.o:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Zydis.c.o
.PHONY : src/Zydis.c.o

src/Zydis.i: src/Zydis.c.i

.PHONY : src/Zydis.i

# target to preprocess a source file
src/Zydis.c.i:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Zydis.c.i
.PHONY : src/Zydis.c.i

src/Zydis.s: src/Zydis.c.s

.PHONY : src/Zydis.s

# target to generate assembly for a file
src/Zydis.c.s:
	$(MAKE) -f CMakeFiles/Zydis.dir/build.make CMakeFiles/Zydis.dir/src/Zydis.c.s
.PHONY : src/Zydis.c.s

tools/ZydisDisasm.o: tools/ZydisDisasm.c.o

.PHONY : tools/ZydisDisasm.o

# target to build an object file
tools/ZydisDisasm.c.o:
	$(MAKE) -f CMakeFiles/ZydisDisasm.dir/build.make CMakeFiles/ZydisDisasm.dir/tools/ZydisDisasm.c.o
.PHONY : tools/ZydisDisasm.c.o

tools/ZydisDisasm.i: tools/ZydisDisasm.c.i

.PHONY : tools/ZydisDisasm.i

# target to preprocess a source file
tools/ZydisDisasm.c.i:
	$(MAKE) -f CMakeFiles/ZydisDisasm.dir/build.make CMakeFiles/ZydisDisasm.dir/tools/ZydisDisasm.c.i
.PHONY : tools/ZydisDisasm.c.i

tools/ZydisDisasm.s: tools/ZydisDisasm.c.s

.PHONY : tools/ZydisDisasm.s

# target to generate assembly for a file
tools/ZydisDisasm.c.s:
	$(MAKE) -f CMakeFiles/ZydisDisasm.dir/build.make CMakeFiles/ZydisDisasm.dir/tools/ZydisDisasm.c.s
.PHONY : tools/ZydisDisasm.c.s

tools/ZydisFuzzDecoder.o: tools/ZydisFuzzDecoder.c.o

.PHONY : tools/ZydisFuzzDecoder.o

# target to build an object file
tools/ZydisFuzzDecoder.c.o:
	$(MAKE) -f CMakeFiles/ZydisFuzzDecoder.dir/build.make CMakeFiles/ZydisFuzzDecoder.dir/tools/ZydisFuzzDecoder.c.o
.PHONY : tools/ZydisFuzzDecoder.c.o

tools/ZydisFuzzDecoder.i: tools/ZydisFuzzDecoder.c.i

.PHONY : tools/ZydisFuzzDecoder.i

# target to preprocess a source file
tools/ZydisFuzzDecoder.c.i:
	$(MAKE) -f CMakeFiles/ZydisFuzzDecoder.dir/build.make CMakeFiles/ZydisFuzzDecoder.dir/tools/ZydisFuzzDecoder.c.i
.PHONY : tools/ZydisFuzzDecoder.c.i

tools/ZydisFuzzDecoder.s: tools/ZydisFuzzDecoder.c.s

.PHONY : tools/ZydisFuzzDecoder.s

# target to generate assembly for a file
tools/ZydisFuzzDecoder.c.s:
	$(MAKE) -f CMakeFiles/ZydisFuzzDecoder.dir/build.make CMakeFiles/ZydisFuzzDecoder.dir/tools/ZydisFuzzDecoder.c.s
.PHONY : tools/ZydisFuzzDecoder.c.s

tools/ZydisFuzzEncoder.o: tools/ZydisFuzzEncoder.c.o

.PHONY : tools/ZydisFuzzEncoder.o

# target to build an object file
tools/ZydisFuzzEncoder.c.o:
	$(MAKE) -f CMakeFiles/ZydisFuzzEncoder.dir/build.make CMakeFiles/ZydisFuzzEncoder.dir/tools/ZydisFuzzEncoder.c.o
.PHONY : tools/ZydisFuzzEncoder.c.o

tools/ZydisFuzzEncoder.i: tools/ZydisFuzzEncoder.c.i

.PHONY : tools/ZydisFuzzEncoder.i

# target to preprocess a source file
tools/ZydisFuzzEncoder.c.i:
	$(MAKE) -f CMakeFiles/ZydisFuzzEncoder.dir/build.make CMakeFiles/ZydisFuzzEncoder.dir/tools/ZydisFuzzEncoder.c.i
.PHONY : tools/ZydisFuzzEncoder.c.i

tools/ZydisFuzzEncoder.s: tools/ZydisFuzzEncoder.c.s

.PHONY : tools/ZydisFuzzEncoder.s

# target to generate assembly for a file
tools/ZydisFuzzEncoder.c.s:
	$(MAKE) -f CMakeFiles/ZydisFuzzEncoder.dir/build.make CMakeFiles/ZydisFuzzEncoder.dir/tools/ZydisFuzzEncoder.c.s
.PHONY : tools/ZydisFuzzEncoder.c.s

tools/ZydisFuzzReEncoding.o: tools/ZydisFuzzReEncoding.c.o

.PHONY : tools/ZydisFuzzReEncoding.o

# target to build an object file
tools/ZydisFuzzReEncoding.c.o:
	$(MAKE) -f CMakeFiles/ZydisFuzzReEncoding.dir/build.make CMakeFiles/ZydisFuzzReEncoding.dir/tools/ZydisFuzzReEncoding.c.o
.PHONY : tools/ZydisFuzzReEncoding.c.o

tools/ZydisFuzzReEncoding.i: tools/ZydisFuzzReEncoding.c.i

.PHONY : tools/ZydisFuzzReEncoding.i

# target to preprocess a source file
tools/ZydisFuzzReEncoding.c.i:
	$(MAKE) -f CMakeFiles/ZydisFuzzReEncoding.dir/build.make CMakeFiles/ZydisFuzzReEncoding.dir/tools/ZydisFuzzReEncoding.c.i
.PHONY : tools/ZydisFuzzReEncoding.c.i

tools/ZydisFuzzReEncoding.s: tools/ZydisFuzzReEncoding.c.s

.PHONY : tools/ZydisFuzzReEncoding.s

# target to generate assembly for a file
tools/ZydisFuzzReEncoding.c.s:
	$(MAKE) -f CMakeFiles/ZydisFuzzReEncoding.dir/build.make CMakeFiles/ZydisFuzzReEncoding.dir/tools/ZydisFuzzReEncoding.c.s
.PHONY : tools/ZydisFuzzReEncoding.c.s

tools/ZydisFuzzShared.o: tools/ZydisFuzzShared.c.o

.PHONY : tools/ZydisFuzzShared.o

# target to build an object file
tools/ZydisFuzzShared.c.o:
	$(MAKE) -f CMakeFiles/ZydisFuzzDecoder.dir/build.make CMakeFiles/ZydisFuzzDecoder.dir/tools/ZydisFuzzShared.c.o
	$(MAKE) -f CMakeFiles/ZydisFuzzEncoder.dir/build.make CMakeFiles/ZydisFuzzEncoder.dir/tools/ZydisFuzzShared.c.o
	$(MAKE) -f CMakeFiles/ZydisFuzzReEncoding.dir/build.make CMakeFiles/ZydisFuzzReEncoding.dir/tools/ZydisFuzzShared.c.o
.PHONY : tools/ZydisFuzzShared.c.o

tools/ZydisFuzzShared.i: tools/ZydisFuzzShared.c.i

.PHONY : tools/ZydisFuzzShared.i

# target to preprocess a source file
tools/ZydisFuzzShared.c.i:
	$(MAKE) -f CMakeFiles/ZydisFuzzDecoder.dir/build.make CMakeFiles/ZydisFuzzDecoder.dir/tools/ZydisFuzzShared.c.i
	$(MAKE) -f CMakeFiles/ZydisFuzzEncoder.dir/build.make CMakeFiles/ZydisFuzzEncoder.dir/tools/ZydisFuzzShared.c.i
	$(MAKE) -f CMakeFiles/ZydisFuzzReEncoding.dir/build.make CMakeFiles/ZydisFuzzReEncoding.dir/tools/ZydisFuzzShared.c.i
.PHONY : tools/ZydisFuzzShared.c.i

tools/ZydisFuzzShared.s: tools/ZydisFuzzShared.c.s

.PHONY : tools/ZydisFuzzShared.s

# target to generate assembly for a file
tools/ZydisFuzzShared.c.s:
	$(MAKE) -f CMakeFiles/ZydisFuzzDecoder.dir/build.make CMakeFiles/ZydisFuzzDecoder.dir/tools/ZydisFuzzShared.c.s
	$(MAKE) -f CMakeFiles/ZydisFuzzEncoder.dir/build.make CMakeFiles/ZydisFuzzEncoder.dir/tools/ZydisFuzzShared.c.s
	$(MAKE) -f CMakeFiles/ZydisFuzzReEncoding.dir/build.make CMakeFiles/ZydisFuzzReEncoding.dir/tools/ZydisFuzzShared.c.s
.PHONY : tools/ZydisFuzzShared.c.s

tools/ZydisInfo.o: tools/ZydisInfo.c.o

.PHONY : tools/ZydisInfo.o

# target to build an object file
tools/ZydisInfo.c.o:
	$(MAKE) -f CMakeFiles/ZydisInfo.dir/build.make CMakeFiles/ZydisInfo.dir/tools/ZydisInfo.c.o
.PHONY : tools/ZydisInfo.c.o

tools/ZydisInfo.i: tools/ZydisInfo.c.i

.PHONY : tools/ZydisInfo.i

# target to preprocess a source file
tools/ZydisInfo.c.i:
	$(MAKE) -f CMakeFiles/ZydisInfo.dir/build.make CMakeFiles/ZydisInfo.dir/tools/ZydisInfo.c.i
.PHONY : tools/ZydisInfo.c.i

tools/ZydisInfo.s: tools/ZydisInfo.c.s

.PHONY : tools/ZydisInfo.s

# target to generate assembly for a file
tools/ZydisInfo.c.s:
	$(MAKE) -f CMakeFiles/ZydisInfo.dir/build.make CMakeFiles/ZydisInfo.dir/tools/ZydisInfo.c.s
.PHONY : tools/ZydisInfo.c.s

tools/ZydisTestEncoderAbsolute.o: tools/ZydisTestEncoderAbsolute.c.o

.PHONY : tools/ZydisTestEncoderAbsolute.o

# target to build an object file
tools/ZydisTestEncoderAbsolute.c.o:
	$(MAKE) -f CMakeFiles/ZydisTestEncoderAbsolute.dir/build.make CMakeFiles/ZydisTestEncoderAbsolute.dir/tools/ZydisTestEncoderAbsolute.c.o
.PHONY : tools/ZydisTestEncoderAbsolute.c.o

tools/ZydisTestEncoderAbsolute.i: tools/ZydisTestEncoderAbsolute.c.i

.PHONY : tools/ZydisTestEncoderAbsolute.i

# target to preprocess a source file
tools/ZydisTestEncoderAbsolute.c.i:
	$(MAKE) -f CMakeFiles/ZydisTestEncoderAbsolute.dir/build.make CMakeFiles/ZydisTestEncoderAbsolute.dir/tools/ZydisTestEncoderAbsolute.c.i
.PHONY : tools/ZydisTestEncoderAbsolute.c.i

tools/ZydisTestEncoderAbsolute.s: tools/ZydisTestEncoderAbsolute.c.s

.PHONY : tools/ZydisTestEncoderAbsolute.s

# target to generate assembly for a file
tools/ZydisTestEncoderAbsolute.c.s:
	$(MAKE) -f CMakeFiles/ZydisTestEncoderAbsolute.dir/build.make CMakeFiles/ZydisTestEncoderAbsolute.dir/tools/ZydisTestEncoderAbsolute.c.s
.PHONY : tools/ZydisTestEncoderAbsolute.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Zydis"
	@echo "... ZydisPerfTest"
	@echo "... Formatter02"
	@echo "... Formatter01"
	@echo "... EncodeFromScratch"
	@echo "... RewriteCode"
	@echo "... install"
	@echo "... ZydisDisasm"
	@echo "... ZydisFuzzDecoder"
	@echo "... ZydisFuzzEncoder"
	@echo "... ZydisTestEncoderAbsolute"
	@echo "... Formatter03"
	@echo "... ZydisFuzzReEncoding"
	@echo "... ZydisInfo"
	@echo "... Zycore"
	@echo "... examples/EncodeFromScratch.o"
	@echo "... examples/EncodeFromScratch.i"
	@echo "... examples/EncodeFromScratch.s"
	@echo "... examples/Formatter01.o"
	@echo "... examples/Formatter01.i"
	@echo "... examples/Formatter01.s"
	@echo "... examples/Formatter02.o"
	@echo "... examples/Formatter02.i"
	@echo "... examples/Formatter02.s"
	@echo "... examples/Formatter03.o"
	@echo "... examples/Formatter03.i"
	@echo "... examples/Formatter03.s"
	@echo "... examples/RewriteCode.o"
	@echo "... examples/RewriteCode.i"
	@echo "... examples/RewriteCode.s"
	@echo "... examples/ZydisPerfTest.o"
	@echo "... examples/ZydisPerfTest.i"
	@echo "... examples/ZydisPerfTest.s"
	@echo "... src/Decoder.o"
	@echo "... src/Decoder.i"
	@echo "... src/Decoder.s"
	@echo "... src/DecoderData.o"
	@echo "... src/DecoderData.i"
	@echo "... src/DecoderData.s"
	@echo "... src/Encoder.o"
	@echo "... src/Encoder.i"
	@echo "... src/Encoder.s"
	@echo "... src/EncoderData.o"
	@echo "... src/EncoderData.i"
	@echo "... src/EncoderData.s"
	@echo "... src/Formatter.o"
	@echo "... src/Formatter.i"
	@echo "... src/Formatter.s"
	@echo "... src/FormatterATT.o"
	@echo "... src/FormatterATT.i"
	@echo "... src/FormatterATT.s"
	@echo "... src/FormatterBase.o"
	@echo "... src/FormatterBase.i"
	@echo "... src/FormatterBase.s"
	@echo "... src/FormatterBuffer.o"
	@echo "... src/FormatterBuffer.i"
	@echo "... src/FormatterBuffer.s"
	@echo "... src/FormatterIntel.o"
	@echo "... src/FormatterIntel.i"
	@echo "... src/FormatterIntel.s"
	@echo "... src/MetaInfo.o"
	@echo "... src/MetaInfo.i"
	@echo "... src/MetaInfo.s"
	@echo "... src/Mnemonic.o"
	@echo "... src/Mnemonic.i"
	@echo "... src/Mnemonic.s"
	@echo "... src/Register.o"
	@echo "... src/Register.i"
	@echo "... src/Register.s"
	@echo "... src/Segment.o"
	@echo "... src/Segment.i"
	@echo "... src/Segment.s"
	@echo "... src/SharedData.o"
	@echo "... src/SharedData.i"
	@echo "... src/SharedData.s"
	@echo "... src/String.o"
	@echo "... src/String.i"
	@echo "... src/String.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/Zydis.o"
	@echo "... src/Zydis.i"
	@echo "... src/Zydis.s"
	@echo "... tools/ZydisDisasm.o"
	@echo "... tools/ZydisDisasm.i"
	@echo "... tools/ZydisDisasm.s"
	@echo "... tools/ZydisFuzzDecoder.o"
	@echo "... tools/ZydisFuzzDecoder.i"
	@echo "... tools/ZydisFuzzDecoder.s"
	@echo "... tools/ZydisFuzzEncoder.o"
	@echo "... tools/ZydisFuzzEncoder.i"
	@echo "... tools/ZydisFuzzEncoder.s"
	@echo "... tools/ZydisFuzzReEncoding.o"
	@echo "... tools/ZydisFuzzReEncoding.i"
	@echo "... tools/ZydisFuzzReEncoding.s"
	@echo "... tools/ZydisFuzzShared.o"
	@echo "... tools/ZydisFuzzShared.i"
	@echo "... tools/ZydisFuzzShared.s"
	@echo "... tools/ZydisInfo.o"
	@echo "... tools/ZydisInfo.i"
	@echo "... tools/ZydisInfo.s"
	@echo "... tools/ZydisTestEncoderAbsolute.o"
	@echo "... tools/ZydisTestEncoderAbsolute.i"
	@echo "... tools/ZydisTestEncoderAbsolute.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

